### ISSUE TITLE
About dialogue cut off

### ISSUE THREAD

**Issue by mygizli04** [Squid4572/JustText#1]
I cannot resize the about dialogue and it appears cut off.
![image](https://user-images.githubusercontent.com/42012824/151678290-34153745-6e8a-4b0f-8a93-8016e5513d46.png)

**Comment by Squid4572** [comment]
Give me a second

**Comment by Squid4572** [comment]
[JustText.app.zip](https://github.com/Squid4572/JustText/files/8055776/JustText.app.zip)
It should work now.

**Comment by Squid4572** [comment]
Thank you for your feedback!
